matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.chef-10
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.chef-11
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.chef-11
script:
  - bundle exec rspec --color --format progress
  - CS_SPEC_TYPE=MiniTest bundle exec cucumber --color --format progress
  - CS_SPEC_TYPE=RSpec bundle exec cucumber --color --format progress
