rvm:
  - ree       # Remove on July 1, 2013
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.chef-11
  - gemfiles/Gemfile.chef-10
notifications:
  irc:
    channels:
      - 'irc.freenode.org#chefspec'
    skip_join: true
    use_notice: true
