rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.chef-11
  - gemfiles/Gemfile.chef-10
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.chef-10
script:
  - bundle exec rspec --color --format progress
  - CS_SPEC_TYPE=MiniTest bundle exec cucumber --color --format progress
  - CS_SPEC_TYPE=RSpec bundle exec cucumber --color --format progress
